# Generated by Django 2.1.5 on 2019-02-27 03:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='材料商名')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='yq1234', max_length=256, verbose_name='地址'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='area',
            field=models.FloatField(blank=True, null=True, verbose_name='面积'),
        ),
        migrations.AddField(
            model_name='customer',
            name='expense_paid',
            field=models.FloatField(blank=True, null=True, verbose_name='开销已出账'),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='电话'),
        ),
        migrations.AddField(
            model_name='customer',
            name='price_discount',
            field=models.FloatField(default=9, verbose_name='折扣'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='price_received',
            field=models.FloatField(blank=True, null=True, verbose_name='报价已到账'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sign_date',
            field=models.DateField(default=datetime.datetime(2019, 2, 27, 3, 53, 27, 679243, tzinfo=utc), verbose_name='签单日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='total_expense',
            field=models.FloatField(blank=True, null=True, verbose_name='总开销'),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_price',
            field=models.FloatField(default=10000, verbose_name='总报价'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=64, verbose_name='客户名'),
        ),
    ]
