# Generated by Django 2.1.5 on 2019-02-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190227_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='duration',
            field=models.IntegerField(default=60, verbose_name='工期'),
            preserve_default=False,
        ),
    ]
