# Generated by Django 2.1.5 on 2019-03-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190302_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='expense_paid',
            field=models.FloatField(blank=True, null=True, verbose_name='总材料费已支付'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='total_expense',
            field=models.FloatField(blank=True, null=True, verbose_name='总材料费'),
        ),
    ]
