# Generated by Django 2.1.5 on 2019-03-03 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190302_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionFromCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='金额')),
                ('collect_date', models.DateField(verbose_name='收款日期')),
                ('remark', models.CharField(max_length=512, verbose_name='备注')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Customer')),
            ],
        ),
    ]
