# Generated by Django 2.1.5 on 2019-03-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_collectionfromcustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionfromcustomer',
            name='remark',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='备注'),
        ),
    ]
