# Generated by Django 2.1.5 on 2019-03-04 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20190303_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialFirstClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='类别名称')),
                ('description', models.CharField(max_length=256, verbose_name='描述')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialSecondClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='类别名称')),
                ('description', models.CharField(max_length=256, verbose_name='描述')),
                ('first_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.MaterialFirstClass')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialThirdClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='类别名称')),
                ('description', models.CharField(max_length=256, verbose_name='描述')),
                ('second_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.MaterialSecondClass')),
            ],
        ),
    ]
