# Generated by Django 2.1.5 on 2019-03-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_materialfirstclass_materialsecondclass_materialthirdclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialsecondclass',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='materialthirdclass',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='描述'),
        ),
    ]
