# Generated by Django 2.1.5 on 2019-03-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20190304_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialfirstclass',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='描述'),
        ),
    ]
