# Generated by Django 2.1.5 on 2019-03-05 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20190304_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionfromcustomer',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Customer', verbose_name='客户'),
        ),
    ]
