# Generated by Django 2.1.5 on 2019-03-05 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20190305_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='材料名称')),
                ('unit', models.CharField(max_length=16, verbose_name='单位')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='描述')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialSupplierRelationShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='单价')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Material', verbose_name='材料')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Supplier', verbose_name='材料商')),
            ],
        ),
        migrations.AlterField(
            model_name='materialsecondclass',
            name='first_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.MaterialFirstClass', verbose_name='一级类别'),
        ),
        migrations.AlterField(
            model_name='materialthirdclass',
            name='second_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.MaterialSecondClass', verbose_name='二级类别'),
        ),
        migrations.AddField(
            model_name='material',
            name='material_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.MaterialThirdClass', verbose_name='类别'),
        ),
        migrations.AddField(
            model_name='material',
            name='suppliers',
            field=models.ManyToManyField(through='account.MaterialSupplierRelationShip', to='account.Supplier'),
        ),
    ]
