# Generated by Django 2.1.7 on 2019-03-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20190315_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='name',
            field=models.CharField(default='', max_length=64, verbose_name='仓库名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='suppliers',
            field=models.ManyToManyField(through='account.MaterialSupplierRelationship', to='account.Supplier'),
        ),
    ]
