# Generated by Django 2.1.7 on 2019-03-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20190315_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialorderitem',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='materialorderitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='materialorderitem',
            name='supplier',
        ),
        migrations.AlterField(
            model_name='material',
            name='suppliers',
            field=models.ManyToManyField(through='account.MaterialSupplierRelationship', to='account.Supplier'),
        ),
    ]
