# Generated by Django 2.1.7 on 2019-03-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20190315_1934'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaterialOrderItem',
            new_name='MaterialOrderDemandItem',
        ),
        migrations.AlterField(
            model_name='material',
            name='suppliers',
            field=models.ManyToManyField(through='account.MaterialSupplierRelationship', to='account.Supplier'),
        ),
    ]
