# Generated by Django 2.1.7 on 2019-03-15 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20190315_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialOrderPurchaseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_type', models.CharField(choices=[('W', 'Warehouse'), ('S', 'Supplier')], max_length=1)),
                ('quantity', models.FloatField(verbose_name='数量')),
                ('price', models.FloatField(verbose_name='单价')),
                ('remark', models.CharField(blank=True, max_length=512, null=True, verbose_name='备注')),
            ],
        ),
        migrations.AlterField(
            model_name='material',
            name='suppliers',
            field=models.ManyToManyField(through='account.MaterialSupplierRelationship', to='account.Supplier'),
        ),
        migrations.AddField(
            model_name='materialorderpurchaseitem',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Material', verbose_name='材料'),
        ),
        migrations.AddField(
            model_name='materialorderpurchaseitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.MaterialOrder', verbose_name='订单'),
        ),
        migrations.AddField(
            model_name='materialorderpurchaseitem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Supplier', verbose_name='材料商'),
        ),
        migrations.AddField(
            model_name='materialorderpurchaseitem',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Warehouse', verbose_name='仓库'),
        ),
    ]
