# Generated by Django 2.1.7 on 2019-03-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20190315_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialorderpurchaseitem',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='已支付'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='suppliers',
            field=models.ManyToManyField(through='account.MaterialSupplierRelationship', to='account.Supplier'),
        ),
    ]
