# Generated by Django 2.1.7 on 2019-03-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20190319_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseinorderrelationship',
            name='expense',
            field=models.FloatField(default=0, verbose_name='总花费'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='suppliers',
            field=models.ManyToManyField(through='account.MaterialSupplierRelationship', to='account.Supplier'),
        ),
    ]
